version: '3.8'

services:
  reelwin-admin:
    container_name: reelwin-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
      # No need to set NEXT_PUBLIC_BASE_PATH since it's in next.config.js
    volumes:
      - ./logs:/app/logs
    networks:
      - reelwin-network
    healthcheck:
      # Update the health check URL to include the base path
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3007/reelwin-admin/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  reelwin-network:
    driver: bridge